# Generated by Django 4.0.6 on 2022-07-30 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listchoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listchoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create date'),
        ),
    ]
